# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=release
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),release)
  Naui_config = release
  Uphonic_config = release
endif

PROJECTS := Naui Uphonic

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

Naui:
ifneq (,$(Naui_config))
	@echo "==== Building Naui ($(Naui_config)) ===="
	@${MAKE} --no-print-directory -C . -f Naui.make config=$(Naui_config)
endif

Uphonic: Naui
ifneq (,$(Uphonic_config))
	@echo "==== Building Uphonic ($(Uphonic_config)) ===="
	@${MAKE} --no-print-directory -C . -f Uphonic.make config=$(Uphonic_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f Naui.make clean
	@${MAKE} --no-print-directory -C . -f Uphonic.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   Naui"
	@echo "   Uphonic"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"